# Generated by Django 5.2.9 on 2026-01-20 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='HTML content for event description')),
                ('start_datetime', models.DateTimeField(help_text='Event start date and time')),
                ('end_datetime', models.DateTimeField(help_text='Event end date and time')),
                ('location', models.CharField(help_text="e.g., 'Chicago, WY82601, US'", max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('tab_content', models.JSONField(blank=True, default=dict, help_text='{"location": "...", "event_target": "..."}')),
                ('what_you_learn', models.JSONField(blank=True, default=list, help_text='List of learning outcomes/features')),
                ('is_published', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True, help_text='External JOIN/registration URL', null=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['is_published', 'start_datetime'], name='events_is_publ_b3ad35_idx'), models.Index(fields=['slug'], name='events_slug_930801_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
