# Generated by Django 5.2.9 on 2026-01-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Google Maps Embed HTML code (<iframe...>)'),
        ),
    ]
