# Generated by Django 5.2.17 on 2026-09-24 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_program_review_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, default='', max_length=254)),
                ('program_code', models.CharField(blank=True, default='', max_length=50)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('operations', models.JSONField(default=list)),
                ('preview', models.JSONField(default=dict)),
                ('target_versions', models.JSONField(default=dict)),
                ('affects_published_content', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('applied', 'Applied'), ('stale', 'Stale'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('expired', 'Expired')], default='prepared', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_course_changes', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('applied_by_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_course_changes', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_course_changes', to='core.program')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_course_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_course_changes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_course_c_user_id_d991f5_idx'), models.Index(fields=['program', '-created_at'], name='ai_course_c_program_2ec8e6_idx'), models.Index(fields=['status'], name='ai_course_c_status_7b211c_idx')],
            },
        ),
    ]
