# Generated by Django 5.2.9 on 2026-01-07 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='core.program')),
            ],
            options={
                'db_table': 'instructor_assignments',
            },
        ),
        migrations.CreateModel(
            name='NodeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('completion_type', models.CharField(choices=[('view', 'View'), ('quiz_pass', 'Quiz Pass'), ('upload', 'Upload'), ('manual', 'Manual')], max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='progression.enrollment')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='curriculum.curriculumnode')),
            ],
            options={
                'db_table': 'node_completions',
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'status'], name='enrollments_user_id_b5f69f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['program', 'status'], name='enrollments_program_973e56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'program')},
        ),
        migrations.AddIndex(
            model_name='instructorassignment',
            index=models.Index(fields=['instructor'], name='instructor__instruc_1ab47c_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorassignment',
            index=models.Index(fields=['program'], name='instructor__program_fa5270_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorassignment',
            unique_together={('instructor', 'program')},
        ),
        migrations.AddIndex(
            model_name='nodecompletion',
            index=models.Index(fields=['enrollment'], name='completions_enrollment_idx'),
        ),
        migrations.AddIndex(
            model_name='nodecompletion',
            index=models.Index(fields=['node'], name='completions_node_idx'),
        ),
        migrations.AddConstraint(
            model_name='nodecompletion',
            constraint=models.UniqueConstraint(fields=('enrollment', 'node'), name='unique_enrollment_node_completion'),
        ),
    ]
