# Generated by Django 5.2.9 on 2025-12-21 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_programs_name_idx_programs_name_c4324d_idx_and_more'),
        ('progression', '0002_nodecompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'instructor_assignments',
            },
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_user_program_enrollment',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_user_id_b5f69f_idx',
            old_name='enrollments_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_program_973e56_idx',
            old_name='enrollments_program_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'program')},
        ),
        migrations.AddField(
            model_name='instructorassignment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorassignment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='core.program'),
        ),
        migrations.AddIndex(
            model_name='instructorassignment',
            index=models.Index(fields=['instructor'], name='instructor__instruc_1ab47c_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorassignment',
            index=models.Index(fields=['program'], name='instructor__program_fa5270_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorassignment',
            unique_together={('instructor', 'program')},
        ),
    ]
