# Generated by Django 5.2.9 on 2026-01-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0003_enrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorassignment',
            name='role',
            field=models.CharField(default='Instructor', max_length=50),
        ),
    ]
