# Generated by Django 5.2.9 on 2026-01-15 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_curriculumnode_is_preview_and_more'),
        ('progression', '0004_add_role_to_instructor_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon name or URL', max_length=100)),
                ('xp_value', models.PositiveIntegerField(default=0, help_text='XP bonus when badge is earned')),
                ('trigger', models.CharField(blank=True, choices=[('lesson_complete', 'Lesson Complete'), ('quiz_pass', 'Quiz Pass'), ('quiz_perfect', 'Perfect Quiz Score'), ('first_try_pass', 'First Try Pass'), ('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('module_complete', 'Module Complete'), ('course_complete', 'Course Complete')], default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'badges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='progression.badge')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='progression.enrollment')),
                ('trigger_node', models.ForeignKey(blank=True, help_text='The curriculum node that triggered this badge', null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.curriculumnode')),
            ],
            options={
                'db_table': 'student_badges',
                'indexes': [models.Index(fields=['enrollment', 'earned_at'], name='student_bad_enrollm_3dd4a1_idx')],
                'unique_together': {('enrollment', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='StudentXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_amount', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('lesson_complete', 'Lesson Complete'), ('quiz_pass', 'Quiz Pass'), ('quiz_perfect', 'Perfect Quiz Score'), ('assignment_submit', 'Assignment Submitted'), ('first_try', 'First Try Bonus'), ('streak_bonus', 'Streak Bonus'), ('badge_earned', 'Badge Earned'), ('manual', 'Manual Award')], max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_logs', to='progression.enrollment')),
                ('source_node', models.ForeignKey(blank=True, help_text='The curriculum node that generated this XP', null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.curriculumnode')),
            ],
            options={
                'db_table': 'student_xp',
                'indexes': [models.Index(fields=['enrollment', 'earned_at'], name='student_xp_enrollm_16d921_idx'), models.Index(fields=['source_node'], name='student_xp_source__3dc96f_idx')],
            },
        ),
    ]
