# Generated by Django 5.2.9 on 2026-01-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_curriculumnode_is_preview_and_more'),
        ('progression', '0005_gamification_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('video_timestamp', models.PositiveIntegerField(blank=True, help_text='Video position in seconds when note was taken', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='progression.enrollment')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='curriculum.curriculumnode')),
            ],
            options={
                'db_table': 'student_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'node'], name='student_not_enrollm_b705b2_idx'), models.Index(fields=['enrollment', '-created_at'], name='student_not_enrollm_37634f_idx')],
            },
        ),
    ]
