# Generated by Django 5.2.14 on 2026-07-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0008_gamification_idempotency_and_streaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodecompletion',
            name='completion_type',
            field=models.CharField(choices=[('view', 'View'), ('quiz_pass', 'Quiz Pass'), ('upload', 'Upload'), ('manual', 'Manual'), ('attendance', 'Verified attendance')], max_length=20),
        ),
    ]
