# Generated by Django 5.2.13 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_wishlistitem"),
        ("core", "0024_program_review_defaults"),
        ("progression", "0009_add_attendance_completion_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("status", models.CharField(choices=[("awaiting_identity", "Awaiting identity"), ("awaiting_payment", "Awaiting payment"), ("awaiting_approval", "Awaiting approval"), ("enrolled", "Enrolled"), ("expired", "Expired"), ("cancelled", "Cancelled")], default="awaiting_identity", max_length=24)),
                ("source", models.CharField(blank=True, default="program_detail", max_length=80)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("enrollment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enrollment_intents", to="progression.enrollment")),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enrollment_intents", to="commerce.order")),
                ("program", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enrollment_intents", to="core.program")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enrollment_intents", to="core.user")),
            ],
            options={
                "db_table": "enrollment_intents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="enroll_intent_status_idx"),
                    models.Index(fields=["program", "-created_at"], name="enroll_intent_program_idx"),
                    models.Index(fields=["email", "-created_at"], name="enroll_intent_email_idx"),
                ],
            },
        ),
    ]
