import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("curriculum", "0005_delete_course_change_request"),
        ("progression", "0008_gamification_idempotency_and_streaks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="ScheduledLearningSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("live_meeting", "Live meeting"), ("live_stream", "Live stream"), ("in_person_session", "In-person session")], max_length=24)),
                ("provider", models.CharField(choices=[("google_meet", "Google Meet"), ("zoom", "Zoom"), ("teams", "Microsoft Teams"), ("youtube", "YouTube Live"), ("vimeo", "Vimeo"), ("custom", "Custom"), ("physical", "Physical venue")], max_length=24)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, default="")),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("source_timezone", models.CharField(max_length=64)),
                ("join_url", models.URLField(blank=True, default="", max_length=1000)),
                ("recording_url", models.URLField(blank=True, default="", max_length=1000)),
                ("passcode_ciphertext", models.TextField(blank=True, default="")),
                ("join_opens_before_minutes", models.PositiveSmallIntegerField(default=15)),
                ("join_closes_after_minutes", models.PositiveSmallIntegerField(default=0)),
                ("venue", models.CharField(blank=True, default="", max_length=255)),
                ("room", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.TextField(blank=True, default="")),
                ("directions", models.TextField(blank=True, default="")),
                ("attendance_instructions", models.TextField(blank=True, default="")),
                ("attendance_threshold_percent", models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ("status", models.CharField(choices=[("scheduled", "Scheduled"), ("cancelled", "Cancelled"), ("completed", "Completed")], default="scheduled", max_length=16)),
                ("provider_event_id", models.CharField(blank=True, default="", max_length=255)),
                ("provider_conference_id", models.CharField(blank=True, default="", max_length=255)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_learning_sessions", to=settings.AUTH_USER_MODEL)),
                ("node", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="scheduled_session", to="curriculum.curriculumnode")),
            ],
            options={"db_table": "live_scheduled_learning_sessions"},
        ),
        migrations.CreateModel(
            name="LiveSessionSyncJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_type", models.CharField(max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("dead", "Dead")], default="pending", max_length=16)),
                ("available_at", models.DateTimeField()),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=8)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("error_category", models.CharField(blank=True, default="", max_length=64)),
                ("last_error", models.TextField(blank=True, default="")),
                ("result", models.JSONField(blank=True, default=dict)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="live_session_sync_jobs", to=settings.AUTH_USER_MODEL)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_jobs", to="live_sessions.scheduledlearningsession")),
            ],
            options={"db_table": "live_session_sync_jobs", "ordering": ["available_at", "id"]},
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("pending", "Pending review"), ("present", "Present"), ("absent", "Absent"), ("excused", "Excused")], default="pending", max_length=16)),
                ("source", models.CharField(choices=[("provider", "Provider verification"), ("instructor_override", "Instructor override"), ("import", "Imported")], default="provider", max_length=24)),
                ("attended_seconds", models.PositiveIntegerField(default=0)),
                ("attendance_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("external_participant_id", models.CharField(blank=True, default="", max_length=255)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="session_attendance", to="progression.enrollment")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="live_sessions.scheduledlearningsession")),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="verified_session_attendance", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "live_session_attendance"},
        ),
        migrations.CreateModel(
            name="SessionAttendanceAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_status", models.CharField(blank=True, default="", max_length=16)),
                ("resulting_status", models.CharField(max_length=16)),
                ("reason", models.TextField()),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="session_attendance_overrides", to=settings.AUTH_USER_MODEL)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="session_attendance_audits", to="progression.enrollment")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_audits", to="live_sessions.scheduledlearningsession")),
            ],
            options={"db_table": "live_session_attendance_audits"},
        ),
        migrations.AddIndex(model_name="scheduledlearningsession", index=models.Index(fields=["kind", "starts_at"], name="live_schedu_kind_a37363_idx")),
        migrations.AddIndex(model_name="scheduledlearningsession", index=models.Index(fields=["status", "starts_at"], name="live_schedu_status_c3e680_idx")),
        migrations.AddIndex(model_name="livesessionsyncjob", index=models.Index(fields=["status", "available_at"], name="live_sessio_status_b21acb_idx")),
        migrations.AddIndex(model_name="livesessionsyncjob", index=models.Index(fields=["session", "job_type", "status"], name="live_sessio_session_968242_idx")),
        migrations.AddIndex(model_name="sessionattendance", index=models.Index(fields=["session", "status"], name="live_sessio_session_2c4422_idx")),
        migrations.AddConstraint(model_name="sessionattendance", constraint=models.UniqueConstraint(fields=("session", "enrollment"), name="live_unique_session_enrollment_attendance")),
        migrations.AddIndex(model_name="sessionattendanceaudit", index=models.Index(fields=["session", "-created_at"], name="live_sessio_session_e27e8d_idx")),
    ]
