# Generated by Django 5.2.9 on 2026-01-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_file_path', models.CharField(max_length=500)),
                ('source_file_name', models.CharField(max_length=255)),
                ('page_count', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_versions',
            },
        ),
        migrations.CreateModel(
            name='ParsedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(max_length=500)),
                ('optimized_path', models.CharField(max_length=500)),
                ('page_number', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parsed_images',
            },
        ),
    ]
