# Generated by Django 5.2.9 on 2026-01-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='curriculum.curriculumnode'),
        ),
        migrations.AddField(
            model_name='parsedimage',
            name='content_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_images', to='content.contentversion'),
        ),
        migrations.AddIndex(
            model_name='contentversion',
            index=models.Index(fields=['node', 'version'], name='cv_node_version_idx'),
        ),
        migrations.AddIndex(
            model_name='contentversion',
            index=models.Index(fields=['is_published'], name='cv_is_published_idx'),
        ),
    ]
