# Generated by Django 5.2.9 on 2026-01-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Rich Text'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'Downloadable File'), ('embed', 'Embed (YouTube/Vimeo)'), ('image', 'Image')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_blocks', to='curriculum.curriculumnode')),
            ],
            options={
                'db_table': 'lesson_blocks',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['node', 'position'], name='lesson_bloc_node_id_0a34d8_idx')],
            },
        ),
    ]
