# Generated by Django 5.2.9 on 2026-01-12 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_lessonblock'),
        ('curriculum', '0002_coursechangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('VIDEO', 'Video'), ('RICHTEXT', 'Rich Text'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment'), ('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('EMBED', 'Embed')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='curriculum.curriculumnode')),
            ],
            options={
                'db_table': 'content_blocks',
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='LessonBlock',
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['node', 'position'], name='content_blo_node_id_007b2e_idx'),
        ),
    ]
