from django.urls import path

from . import views

app_name = "learning_operations"

urlpatterns = [
    path("student/", views.StudentOperationsView.as_view(), name="student"),
    path(
        "programs/<int:program_id>/delivery/",
        views.CourseDeliveryProfileView.as_view(),
        name="delivery",
    ),
    path(
        "programs/<int:program_id>/summary/",
        views.ProgramOperationsSummaryView.as_view(),
        name="summary",
    ),
    path(
        "programs/<int:program_id>/learners/",
        views.ProgramLearnersView.as_view(),
        name="learners",
    ),
    path(
        "programs/<int:program_id>/learners/<int:enrollment_id>/",
        views.ProgramLearnerDetailView.as_view(),
        name="learner-detail",
    ),
    path(
        "programs/<int:program_id>/engagement-matrix/",
        views.ProgramEngagementMatrixView.as_view(),
        name="engagement-matrix",
    ),
    path(
        "programs/<int:program_id>/revenue/",
        views.ProgramRevenueView.as_view(),
        name="revenue",
    ),
    path(
        "quiz-attempts/<int:attempt_id>/manual-grade/",
        views.ManualQuizGradeView.as_view(),
        name="manual-quiz-grade",
    ),
    path(
        "programs/<int:program_id>/invitations/",
        views.CourseLearnerInviteView.as_view(),
        name="course-invitations",
    ),
    path(
        "programs/<int:program_id>/invitations/bulk/",
        views.CourseInvitationBulkActionView.as_view(),
        name="course-invitations-bulk",
    ),
    path(
        "programs/<int:program_id>/roster/preview/",
        views.CourseRosterPreviewView.as_view(),
        name="roster-preview",
    ),
    path(
        "programs/<int:program_id>/roster/import/",
        views.CourseRosterImportView.as_view(),
        name="roster-import",
    ),
    path(
        "programs/<int:program_id>/roster/export/",
        views.CourseRosterExportView.as_view(),
        name="roster-export",
    ),
    path(
        "programs/<int:program_id>/learners/bulk/",
        views.CourseBulkLearnerActionView.as_view(),
        name="learner-bulk",
    ),
    path(
        "programs/<int:program_id>/learners/<int:enrollment_id>/nodes/<int:node_id>/reset/",
        views.LessonCompletionResetView.as_view(),
        name="lesson-completion-reset",
    ),
    path(
        "programs/<int:program_id>/learners/<int:enrollment_id>/quizzes/<int:quiz_id>/grant-attempt/",
        views.QuizAttemptGrantView.as_view(),
        name="quiz-attempt-grant",
    ),
    path(
        "programs/<int:program_id>/assignments/submissions/<int:submission_id>/return/",
        views.AssignmentReturnView.as_view(),
        name="assignment-return",
    ),
    path(
        "invitations/<str:token>/",
        views.InvitationAcceptanceView.as_view(),
        name="invitation-accept",
    ),
]
