# Generated by Django 5.2.9 on 2026-01-09 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instructorcertification_instructorprofile_and_more'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_change_requests', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, help_text='Specific node the feedback relates to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='curriculum.curriculumnode')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='core.program')),
            ],
            options={
                'db_table': 'course_change_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['program', 'is_resolved'], name='course_chan_program_46b952_idx')],
            },
        ),
    ]
