# Generated by Django 5.2.9 on 2025-12-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='curriculumnode',
            new_name='curriculum__program_d560a2_idx',
            old_name='curriculum__program_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='curriculumnode',
            new_name='curriculum__node_ty_76f5e9_idx',
            old_name='curriculum__node_type_idx',
        ),
    ]
