# Generated by Django 5.2.9 on 2026-01-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_coursechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumnode',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Allow non-enrolled users to view'),
        ),
        migrations.AddField(
            model_name='curriculumnode',
            name='unlock_after_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days after enrollment to unlock', null=True),
        ),
        migrations.AddField(
            model_name='curriculumnode',
            name='unlock_date',
            field=models.DateTimeField(blank=True, help_text='Absolute date when content unlocks', null=True),
        ),
    ]
