# Generated by Django 5.2.9 on 2026-01-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_curriculumnode_is_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechangerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
