# Generated by Django 5.2.9 on 2026-01-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='My Institution', max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('deployment_mode', models.CharField(choices=[('tvet', 'TVET Institution (CDACC/KNEC)'), ('theology', 'Theology/Bible School'), ('nita', 'NITA Trade Test'), ('driving', 'Driving School (NTSA)'), ('cbc', 'CBC K-12 School'), ('online', 'Online Courses (Self-Paced)'), ('custom', 'Custom Configuration')], default='custom', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('custom_css', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=dict, help_text="Feature toggles: {'certificates': true, 'gamification': false, ...}")),
                ('is_setup_complete', models.BooleanField(default=False, help_text='Has the initial setup wizard been completed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_blueprint', models.ForeignKey(blank=True, help_text='The academic blueprint defining curriculum structure and grading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settings', to='blueprints.academicblueprint')),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='PresetBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('regulatory_body', models.CharField(blank=True, max_length=255, null=True)),
                ('hierarchy_labels', models.JSONField()),
                ('grading_config', models.JSONField()),
                ('structure_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'preset_blueprints',
                'indexes': [models.Index(fields=['code'], name='preset_blue_code_848d49_idx'), models.Index(fields=['is_active'], name='preset_blue_is_acti_c8ca19_idx')],
            },
        ),
    ]
