# Generated by Django 5.2.9 on 2026-01-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_seed_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='course_levels',
            field=models.JSONField(blank=True, default=list, help_text='Course difficulty levels: [{"value": "beginner", "label": "Beginner"}, ...]'),
        ),
    ]
