# Generated by Django 5.2.9 on 2025-12-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_seed_presets'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='presetblueprint',
            new_name='preset_blue_code_848d49_idx',
            old_name='preset_blue_code_idx',
        ),
        migrations.RenameIndex(
            model_name='presetblueprint',
            new_name='preset_blue_is_acti_c8ca19_idx',
            old_name='preset_blue_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_subdoma_69cf01_idx',
            old_name='tenants_subdoma_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_is_acti_ec1713_idx',
            old_name='tenants_is_acti_idx',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
