# Generated by Django 5.2.9 on 2026-01-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_course_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='program_categories',
            field=models.JSONField(blank=True, default=list, help_text='List of available program categories: ["Biblical Studies", "Theology", ...]'),
        ),
    ]
