# Generated by Django 5.2.9 on 2026-04-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_platformsettings_public_content_social_links'),
        ('platform', '0006_normalize_seeded_preset_hierarchies'),
    ]

    operations = [
    ]
