# Generated by Django 5.2.9 on 2026-01-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_remove_tenant_fk'),
        ('core', '0004_remove_tenant_fk'),
        ('platform', '0007_rename_cct_to_generic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantbranding',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='TenantBranding',
        ),
    ]
