# Generated by Django 5.2.14 on 2026-06-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0009_add_exam_body_presets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='deployment_mode',
            field=models.CharField(choices=[('tvet', 'TVET Institution (KASNEB/CDACC/KNEC/NITA/ICM)'), ('theology', 'Theology/Bible School'), ('driving', 'Driving School (NTSA)'), ('cbc', 'CBC K-12 School'), ('online', 'Online Courses (Self-Paced)'), ('custom', 'Custom Configuration')], default='custom', max_length=20),
        ),
    ]
