# Generated by Django 5.2.9 on 2026-01-09 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'instructor_certifications',
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('bio', models.TextField(blank=True, default='')),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('resume_path', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('teaching_experience', models.TextField(blank=True, default='')),
                ('why_teach_here', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'instructor_profiles',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='submission_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['submission_status'], name='programs_submiss_4be627_idx'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_instructor_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorcertification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.instructorprofile'),
        ),
        migrations.AddIndex(
            model_name='instructorprofile',
            index=models.Index(fields=['status'], name='instructor__status_b9091c_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorprofile',
            index=models.Index(fields=['user'], name='instructor__user_id_31420a_idx'),
        ),
    ]
