# Generated by Django 5.2.9 on 2026-01-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_program_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='custom_pricing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='program',
            name='faq',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='notices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
