# Generated by Django 5.2.9 on 2026-01-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_programs_name_idx_programs_name_c4324d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
    ]
