# Generated by Django 5.2.9 on 2026-01-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_program_custom_pricing_program_faq_program_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('special', 'Special')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, help_text='Total duration in hours'),
        ),
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='programs/thumbnails/'),
        ),
        migrations.AddField(
            model_name='program',
            name='video_hours',
            field=models.PositiveIntegerField(default=0, help_text='Video content duration in hours'),
        ),
        migrations.AddField(
            model_name='program',
            name='what_you_learn',
            field=models.JSONField(blank=True, default=list, help_text='List of learning outcomes'),
        ),
    ]
