# Generated by Django 5.2.9 on 2026-01-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_program_display_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(blank=True, default='beginner', max_length=50),
        ),
    ]
