# Generated by Django 5.2.9 on 2026-01-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(default='TEMP-CODE', error_messages={'unique': 'A program with this code already exists.'}, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
