# Generated by Django 5.2.9 on 2026-01-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_program_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='programs/resources/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('resource_type', models.CharField(default='material', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.program')),
            ],
            options={
                'db_table': 'program_resources',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
