# Generated by Django 5.2.9 on 2026-01-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_programresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
