# Generated by Django 5.2.14 on 2026-05-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_program_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('preferred_campus', models.CharField(max_length=120)),
                ('preferred_programme', models.CharField(max_length=255)),
                ('intake', models.CharField(blank=True, default='', max_length=120)),
                ('education_level', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='website', max_length=80)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'admission_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='admission_a_status_467432_idx'), models.Index(fields=['preferred_campus'], name='admission_a_preferr_b058e5_idx')],
            },
        ),
    ]
