# Generated by Django 5.2.14 on 2026-06-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_virtual_campus_admissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='approval_status',
            field=models.CharField(blank=True, help_text='Regulatory approval: Approved, Pending, Internal Preparation', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='assessment_mode',
            field=models.CharField(blank=True, help_text='Assessment method: Exam, CBET, Trade Test, Assignment, Project', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='award_type',
            field=models.CharField(blank=True, help_text='Award issued: Craft Certificate, Diploma, Government Trade Test Certificate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='centre_status',
            field=models.CharField(blank=True, help_text='Centre approval status (ICM only): ICM Approved Centre, Pending, N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='exam_body',
            field=models.CharField(blank=True, help_text='Examining/awarding body: KASNEB, CDACC, KNEC, NITA, ICM, Internal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='kenya_recognition_status',
            field=models.CharField(blank=True, help_text='TVETA recognition: TVETA-listed, Pending, Not Confirmed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='official_level',
            field=models.CharField(blank=True, help_text='Specific level/stage: Foundation, Level I, Grade III, Level 5, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='qualification_family',
            field=models.CharField(blank=True, help_text='Official category: Certificate, Diploma, Professional, Trade Test, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='source_document',
            field=models.TextField(blank=True, help_text='Reference: Syllabus, TVETA record, approval letter', null=True),
        ),
    ]
