# Generated by Django 5.2.14 on 2026-06-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_exam_body_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='program',
            name='centre_status',
        ),
        migrations.RemoveField(
            model_name='program',
            name='kenya_recognition_status',
        ),
        migrations.RemoveField(
            model_name='program',
            name='source_document',
        ),
    ]
