# Generated by Django 5.2.14 on 2026-07-06 10:28

from decimal import Decimal
from django.db import migrations, models


def seed_default_review_stats(apps, schema_editor):
    Program = apps.get_model("core", "Program")
    Program.objects.filter(rating_average=0, rating_count=0).update(
        rating_average=Decimal("4.00"),
        rating_count=60,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_masterstudy_settings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=3),
        ),
        migrations.AlterField(
            model_name='program',
            name='rating_count',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.RunPython(seed_default_review_stats, noop_reverse),
    ]
