# Generated by Django 5.2.14 on 2026-09-26 11:28

import apps.core.intro_video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_program_review_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='audience_html',
            field=models.TextField(blank=True, default='', help_text="Rich text 'Who this course is for' HTML"),
        ),
        migrations.AddField(
            model_name='program',
            name='intro_video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube, Vimeo, or direct .mp4/.webm intro video for the public course page.', max_length=500, validators=[apps.core.intro_video.validate_intro_video_url]),
        ),
        migrations.AddField(
            model_name='program',
            name='requirements_html',
            field=models.TextField(blank=True, default='', help_text='Rich text course requirements HTML'),
        ),
    ]
