# Generated by Django 5.2.9 on 2026-01-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_add_rubric_model'),
        ('assessments', '0004_quiz_randomize_questions_quiz_retake_penalty_percent_and_more'),
    ]

    operations = [
    ]
