# Generated by Django 5.2.9 on 2026-01-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_merge_20260121_1401'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rubric',
            new_name='assessments_scope_79e54f_idx',
            old_name='assessments_rubrics_scope_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='rubric',
            new_name='assessments_program_bcd8cb_idx',
            old_name='assessments_rubrics_program_idx',
        ),
    ]
