# Generated by Codex on 2026-04-15

from django.db import migrations


def reset_quiz_retake_penalties(apps, schema_editor):
    Quiz = apps.get_model("assessments", "Quiz")
    Quiz.objects.exclude(retake_penalty_percent=0).update(retake_penalty_percent=0)


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0016_normalize_assessment_text_content"),
    ]

    operations = [
        migrations.RunPython(
            reset_quiz_retake_penalties,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
