# Generated by Django 5.2.13 on 2026-04-15 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_reset_quiz_retake_penalties'),
        ('progression', '0007_enrollment_access_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('file', 'File'), ('audio', 'Audio'), ('video', 'Video')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assignment_review_media',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('file', 'File'), ('audio', 'Audio'), ('video', 'Video')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assignment_submission_media',
            },
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='pass_threshold',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_retake_after_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned for Revision')], default='started', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('enrollment', 'assignment', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['enrollment', 'assignment', 'attempt_number'], name='assignment__enrollm_bbefdf_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['enrollment', 'assignment', 'is_official'], name='assignment__enrollm_28fdf3_idx'),
        ),
        migrations.AddField(
            model_name='assignmentreviewmedia',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_media_assets', to='assessments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='assignmentreviewmedia',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_review_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionmedia',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='assessments.assignmentsubmission'),
        ),
        migrations.AddIndex(
            model_name='assignmentreviewmedia',
            index=models.Index(fields=['submission', 'media_type'], name='assignment__submiss_739c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmissionmedia',
            index=models.Index(fields=['submission', 'media_type'], name='assignment__submiss_d616dc_idx'),
        ),
    ]
