# Generated by Django 5.2.13 on 2026-04-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_assignmentreviewmedia_assignmentsubmissionmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='points_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
