# Generated by Django 5.2.14 on 2026-07-16 11:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_question_bank_snapshots(apps, schema_editor):
    Entry = apps.get_model('assessments', 'QuestionBankEntry')
    Revision = apps.get_model('assessments', 'QuestionBankEntryRevision')
    Option = apps.get_model('assessments', 'QuestionOption')
    MatchingPair = apps.get_model('assessments', 'QuestionMatchingPair')
    GapAnswer = apps.get_model('assessments', 'QuestionGapAnswer')
    ImagePair = apps.get_model('assessments', 'QuestionImageMatchingPair')
    Question = apps.get_model('assessments', 'Question')
    Attempt = apps.get_model('assessments', 'QuizAttempt')
    AttemptSnapshot = apps.get_model('assessments', 'QuizAttemptQuestionSnapshot')

    def snapshot_for(question):
        return {
            'version': 1,
            'question_type': question.question_type,
            'text': question.text,
            'points': question.points,
            'answer_data': question.answer_data or {},
            'options': [
                {
                    'key': option.id,
                    'text': option.text,
                    'is_correct': option.is_correct,
                    'position': option.position,
                }
                for option in Option.objects.filter(question_id=question.id).order_by('position')
            ],
            'matching_pairs': [
                {
                    'key': pair.id,
                    'left_text': pair.left_text,
                    'right_text': pair.right_text,
                    'explanation': pair.explanation,
                    'position': pair.position,
                }
                for pair in MatchingPair.objects.filter(question_id=question.id).order_by('position')
            ],
            'gap_answers': [
                {
                    'key': gap.id,
                    'gap_index': gap.gap_index,
                    'accepted_answers': gap.accepted_answers or [],
                    'explanation': gap.explanation,
                }
                for gap in GapAnswer.objects.filter(question_id=question.id).order_by('gap_index')
            ],
            'image_matching_pairs': [
                {
                    'key': pair.id,
                    'question_text': pair.question_text,
                    'question_image': pair.question_image,
                    'answer_text': pair.answer_text,
                    'answer_image': pair.answer_image,
                    'explanation': pair.explanation,
                    'position': pair.position,
                }
                for pair in ImagePair.objects.filter(question_id=question.id).order_by('position')
            ],
        }

    revisions = []
    for entry in Entry.objects.select_related('question').iterator():
        question = entry.question
        if question is None:
            continue
        snapshot = {
            'version': 1,
            'question_type': question.question_type,
            'text': question.text,
            'points': question.points,
            'answer_data': question.answer_data or {},
            'options': [
                {
                    'key': option.id,
                    'text': option.text,
                    'is_correct': option.is_correct,
                    'position': option.position,
                }
                for option in Option.objects.filter(question_id=question.id).order_by('position')
            ],
            'matching_pairs': [
                {
                    'key': pair.id,
                    'left_text': pair.left_text,
                    'right_text': pair.right_text,
                    'explanation': pair.explanation,
                    'position': pair.position,
                }
                for pair in MatchingPair.objects.filter(question_id=question.id).order_by('position')
            ],
            'gap_answers': [
                {
                    'key': gap.id,
                    'gap_index': gap.gap_index,
                    'accepted_answers': gap.accepted_answers or [],
                    'explanation': gap.explanation,
                }
                for gap in GapAnswer.objects.filter(question_id=question.id).order_by('gap_index')
            ],
            'image_matching_pairs': [
                {
                    'key': pair.id,
                    'question_text': pair.question_text,
                    'question_image': pair.question_image,
                    'answer_text': pair.answer_text,
                    'answer_image': pair.answer_image,
                    'explanation': pair.explanation,
                    'position': pair.position,
                }
                for pair in ImagePair.objects.filter(question_id=question.id).order_by('position')
            ],
        }
        entry.question_snapshot = snapshot
        entry.snapshot_version = 1
        entry.save(update_fields=['question_snapshot', 'snapshot_version'])
        revisions.append(
            Revision(
                entry_id=entry.id,
                version=1,
                snapshot=snapshot,
                changed_by_id=entry.owner_id,
            )
        )
    Revision.objects.bulk_create(revisions, ignore_conflicts=True)
    attempt_rows = []
    for attempt in Attempt.objects.iterator():
        for position, question in enumerate(
            Question.objects.filter(quiz_id=attempt.quiz_id).order_by('position', 'id')
        ):
            attempt_rows.append(
                AttemptSnapshot(
                    attempt_id=attempt.id,
                    question_key=question.id,
                    position=position,
                    snapshot=snapshot_for(question),
                    source_question_id=question.id,
                    source_bank_entry_id=question.source_bank_entry_id,
                )
            )
        if len(attempt_rows) >= 1000:
            AttemptSnapshot.objects.bulk_create(attempt_rows, ignore_conflicts=True)
            attempt_rows = []
    AttemptSnapshot.objects.bulk_create(attempt_rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_quiz_mastery_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_bank_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_copies', to='assessments.questionbankentry'),
        ),
        migrations.AddField(
            model_name='questionbankentry',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbankentry',
            name='question_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='questionbankentry',
            name='snapshot_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionbankentry',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_entries', to='assessments.question'),
        ),
        migrations.CreateModel(
            name='QuizQuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(blank=True, choices=[('', 'Any'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='', max_length=20)),
                ('question_type', models.CharField(blank=True, choices=[('', 'Any'), ('mcq', 'Multiple Choice'), ('mcq_multi', 'Multiple Choice (Multi-Select)'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('matching', 'Matching'), ('image_matching', 'Image Matching'), ('fill_blank', 'Fill in the Blank'), ('ordering', 'Ordering/Sequence')], default='', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_pools', to='assessments.questionbank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quiz_question_pools', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_pools', to='assessments.quiz')),
            ],
            options={
                'db_table': 'quiz_question_pools',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptQuestionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.BigIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('manual_points_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('manual_feedback', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_snapshots', to='assessments.quizattempt')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quiz_question_snapshots', to=settings.AUTH_USER_MODEL)),
                ('source_bank_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_snapshots', to='assessments.questionbankentry')),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_snapshots', to='assessments.question')),
                ('source_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_snapshots', to='assessments.quizquestionpool')),
            ],
            options={
                'db_table': 'quiz_attempt_question_snapshots',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('copy', 'Quiz copy'), ('pool_link', 'Pool link'), ('attempt_selection', 'Attempt selection')], max_length=24)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_usage', to='assessments.quizattempt')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='assessments.questionbankentry')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_usage', to='assessments.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_usage', to='assessments.quiz')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='assessments.quizquestionpool')),
            ],
            options={
                'db_table': 'question_bank_usage',
            },
        ),
        migrations.CreateModel(
            name='QuestionBankEntryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_revisions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='assessments.questionbankentry')),
            ],
            options={
                'db_table': 'question_bank_entry_revisions',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'version'), name='unique_question_bank_entry_revision')],
            },
        ),
        migrations.RunPython(backfill_question_bank_snapshots, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='quizquestionpool',
            index=models.Index(fields=['quiz', 'is_active'], name='quiz_questi_quiz_id_be7ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestionpool',
            index=models.Index(fields=['bank'], name='quiz_questi_bank_id_3f28e2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattemptquestionsnapshot',
            index=models.Index(fields=['attempt', 'position'], name='quiz_attemp_attempt_db9183_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizattemptquestionsnapshot',
            constraint=models.UniqueConstraint(fields=('attempt', 'question_key'), name='unique_attempt_question_snapshot_key'),
        ),
        migrations.AddConstraint(
            model_name='quizattemptquestionsnapshot',
            constraint=models.UniqueConstraint(fields=('attempt', 'position'), name='unique_attempt_question_snapshot_position'),
        ),
        migrations.AddIndex(
            model_name='questionbankusage',
            index=models.Index(fields=['entry', '-used_at'], name='question_ba_entry_i_9d6630_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankusage',
            index=models.Index(fields=['quiz', 'usage_type'], name='question_ba_quiz_id_517c8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbankusage',
            constraint=models.UniqueConstraint(condition=models.Q(('usage_type', 'copy')), fields=('usage_type', 'entry', 'question'), name='unique_question_bank_copy_usage'),
        ),
        migrations.AddConstraint(
            model_name='questionbankusage',
            constraint=models.UniqueConstraint(condition=models.Q(('usage_type', 'pool_link')), fields=('usage_type', 'entry', 'pool'), name='unique_question_bank_pool_usage'),
        ),
        migrations.AddConstraint(
            model_name='questionbankusage',
            constraint=models.UniqueConstraint(condition=models.Q(('usage_type', 'attempt_selection')), fields=('usage_type', 'entry', 'attempt'), name='unique_question_bank_attempt_usage'),
        ),
    ]
