# Generated by Django 5.2.14 on 2026-09-26 04:05
"""
Add question bank scopes (course, instructor library, shared).

Existing banks become course banks. Reversing this migration fails while any
instructor-library or shared bank exists, because those banks have no course;
move or delete them before rolling back.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_source_versions(apps, schema_editor):
    """Record the current bank version on existing copies so none look outdated."""
    Question = apps.get_model('assessments', 'Question')
    Entry = apps.get_model('assessments', 'QuestionBankEntry')
    linked_entry_ids = (
        Question.objects.filter(
            source_bank_entry__isnull=False,
            source_bank_entry_version__isnull=True,
        )
        .values_list('source_bank_entry_id', flat=True)
        .distinct()
    )
    versions = Entry.objects.filter(pk__in=list(linked_entry_ids)).values_list(
        'pk', 'snapshot_version'
    )
    for entry_id, version in versions.iterator():
        Question.objects.filter(
            source_bank_entry_id=entry_id,
            source_bank_entry_version__isnull=True,
        ).update(source_bank_entry_version=version)


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_complete_question_banks'),
        ('core', '0024_program_review_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_bank_entry_version',
            field=models.PositiveIntegerField(blank=True, help_text='Bank entry version this copy was taken from', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='scope',
            field=models.CharField(choices=[('course', 'Course'), ('instructor', 'Instructor library'), ('institution', 'Shared')], default='course', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_question_banks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Required for course banks; empty for library and shared banks', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='core.program'),
        ),
        migrations.AlterField(
            model_name='questionbankentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['scope', 'program'], name='question_bank_scope_prog_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['scope', 'owner'], name='question_bank_scope_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'course'), _negated=True), ('program__isnull', False), _connector='OR'), name='question_bank_course_requires_program'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.CheckConstraint(condition=models.Q(('scope', 'course'), ('program__isnull', True), _connector='OR'), name='question_bank_shared_has_no_program'),
        ),
        migrations.AlterField(
            model_name='quizquestionpool',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quiz_question_pools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_source_versions, migrations.RunPython.noop),
    ]
