# Generated by Django 5.2.14 on 2026-09-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0022_question_bank_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, default=''),
        ),
    ]
