# Generated by Django 5.2.14 on 2026-07-16 10:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_learning_operations(apps, schema_editor):
    Program = apps.get_model("core", "Program")
    PlatformSettings = apps.get_model("platform", "PlatformSettings")
    Enrollment = apps.get_model("progression", "Enrollment")
    NodeCompletion = apps.get_model("progression", "NodeCompletion")
    QuizAttempt = apps.get_model("assessments", "QuizAttempt")
    AssignmentSubmission = apps.get_model("assessments", "AssignmentSubmission")
    CourseDeliveryProfile = apps.get_model(
        "learning_operations", "CourseDeliveryProfile"
    )
    EnrollmentLearningActivity = apps.get_model(
        "learning_operations", "EnrollmentLearningActivity"
    )
    LearningActivityDay = apps.get_model("learning_operations", "LearningActivityDay")

    platform = PlatformSettings.objects.order_by("pk").first()
    delivery_mode = "self_paced" if platform and platform.deployment_mode == "online" else "in_person"
    CourseDeliveryProfile.objects.bulk_create(
        [
            CourseDeliveryProfile(program_id=program_id, delivery_mode=delivery_mode)
            for program_id in Program.objects.values_list("id", flat=True)
        ],
        ignore_conflicts=True,
    )

    event_rows = []
    event_rows.extend(
        (enrollment_id, occurred_at, "node_completion")
        for enrollment_id, occurred_at in NodeCompletion.objects.values_list(
            "enrollment_id", "completed_at"
        )
        if occurred_at
    )
    event_rows.extend(
        (enrollment_id, submitted_at or started_at, "quiz_submission" if submitted_at else "quiz_start")
        for enrollment_id, started_at, submitted_at in QuizAttempt.objects.values_list(
            "enrollment_id", "started_at", "submitted_at"
        )
        if submitted_at or started_at
    )
    event_rows.extend(
        (enrollment_id, submitted_at, "assignment_submission")
        for enrollment_id, submitted_at in AssignmentSubmission.objects.values_list(
            "enrollment_id", "submitted_at"
        )
        if submitted_at
    )

    summary = {}
    days = {}
    for enrollment_id, occurred_at, source in event_rows:
        current = summary.setdefault(
            enrollment_id,
            {"first": occurred_at, "last": occurred_at, "source": source},
        )
        if occurred_at < current["first"]:
            current["first"] = occurred_at
        if occurred_at >= current["last"]:
            current["last"] = occurred_at
            current["source"] = source

        key = (enrollment_id, timezone.localdate(occurred_at))
        day = days.setdefault(
            key,
            {"first": occurred_at, "last": occurred_at, "count": 0, "sources": []},
        )
        day["first"] = min(day["first"], occurred_at)
        day["last"] = max(day["last"], occurred_at)
        day["count"] += 1
        if source not in day["sources"]:
            day["sources"].append(source)

    EnrollmentLearningActivity.objects.bulk_create(
        [
            EnrollmentLearningActivity(
                enrollment_id=enrollment_id,
                started_at=data["first"],
                last_activity_at=data["last"],
                last_source=data["source"],
            )
            for enrollment_id, data in summary.items()
        ],
        ignore_conflicts=True,
    )
    LearningActivityDay.objects.bulk_create(
        [
            LearningActivityDay(
                enrollment_id=enrollment_id,
                activity_date=activity_date,
                first_activity_at=data["first"],
                last_activity_at=data["last"],
                event_count=data["count"],
                sources=data["sources"],
            )
            for (enrollment_id, activity_date), data in days.items()
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0020_quiz_mastery_policies'),
        ('core', '0022_masterstudy_settings_fields'),
        ('platform', '0010_remove_nita_deployment_mode'),
        ('progression', '0007_enrollment_access_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_mode', models.CharField(choices=[('self_paced', 'Self-paced'), ('live_online', 'Live online'), ('blended', 'Blended'), ('in_person', 'In person')], default='in_person', max_length=24)),
                ('gamification_opt_in', models.BooleanField(default=False)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to='core.program')),
            ],
            options={
                'db_table': 'learning_course_delivery_profiles',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentLearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_source', models.CharField(blank=True, default='', max_length=64)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activity', to='progression.enrollment')),
            ],
            options={
                'db_table': 'learning_enrollment_activity',
                'indexes': [models.Index(fields=['last_activity_at'], name='learning_en_last_ac_189036_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.DateField()),
                ('first_activity_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('event_count', models.PositiveIntegerField(default=1)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activity_days', to='progression.enrollment')),
            ],
            options={
                'db_table': 'learning_activity_days',
                'indexes': [models.Index(fields=['enrollment', '-activity_date'], name='learning_ac_enrollm_9a9b09_idx'), models.Index(fields=['activity_date'], name='learning_ac_activit_5b5015_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'activity_date'), name='learning_unique_enrollment_activity_day')],
            },
        ),
        migrations.CreateModel(
            name='ManualQuizGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_awarded', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_grades', to='assessments.quizattempt')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_quiz_grades', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_grades', to='assessments.question')),
            ],
            options={
                'db_table': 'learning_manual_quiz_grades',
                'indexes': [models.Index(fields=['attempt', 'graded_at'], name='learning_ma_attempt_679a2f_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='learning_unique_manual_attempt_question')],
            },
        ),
        migrations.RunPython(backfill_learning_operations, migrations.RunPython.noop),
    ]
