# Generated by Django 5.2.14 on 2026-07-16 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_quiz_mastery_policies'),
        ('core', '0022_masterstudy_settings_fields'),
        ('learning_operations', '0001_initial'),
        ('progression', '0007_enrollment_access_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttemptGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=16)),
                ('extra_attempts', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('reason', models.TextField(blank=True, default='')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_grants', to='assessments.assignment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_grants', to='progression.enrollment')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_assessment_attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_grants', to='assessments.quiz')),
            ],
            options={
                'db_table': 'learning_assessment_attempt_grants',
                'indexes': [models.Index(fields=['enrollment', 'assessment_type'], name='learning_as_enrollm_3e37e7_idx'), models.Index(fields=['quiz'], name='learning_as_quiz_id_3eb30b_idx'), models.Index(fields=['assignment'], name='learning_as_assignm_bf2099_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentattemptgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assessment_type', 'quiz'), ('assignment__isnull', True), ('quiz__isnull', False)), models.Q(('assessment_type', 'assignment'), ('assignment__isnull', False), ('quiz__isnull', True)), _connector='OR'), name='learning_attempt_grant_target_matches_type'),
        ),
        migrations.CreateModel(
            name='CourseInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to='progression.enrollment')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_course_invitations', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_invitations', to='core.program')),
            ],
            options={
                'db_table': 'learning_course_invitations',
                'indexes': [models.Index(fields=['program', 'email'], name='learning_co_program_2e62bb_idx'), models.Index(fields=['expires_at'], name='learning_co_expires_74318a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearnerManagementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('resulting_state', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_management_actions', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_audits', to='progression.enrollment')),
            ],
            options={
                'db_table': 'learning_learner_management_audits',
                'indexes': [models.Index(fields=['enrollment', '-created_at'], name='learning_le_enrollm_4507bc_idx')],
            },
        ),
    ]
