# Generated by Django 5.2.9 on 2026-01-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0002_practicumsubmission_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
