# Generated by Django 5.2.13 on 2026-04-11 20:54

import apps.commerce.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_commerce_data(apps, schema_editor):
    Order = apps.get_model("commerce", "Order")
    OrderItem = apps.get_model("commerce", "OrderItem")
    ProgramAccessGrant = apps.get_model("commerce", "ProgramAccessGrant")
    CommerceConfiguration = apps.get_model("commerce", "CommerceConfiguration")
    WebhookEvent = apps.get_model("commerce", "WebhookEvent")
    Enrollment = apps.get_model("progression", "Enrollment")

    CommerceConfiguration.objects.get_or_create(singleton_key="default")

    for event in WebhookEvent.objects.all().iterator():
        payload = event.payload or {}
        event_type = str(payload.get("event") or "")
        if event_type and event.event_type != event_type:
            event.event_type = event_type
            event.save(update_fields=["event_type", "updated_at"])

    for order in Order.objects.all().iterator():
        legacy_total = order.amount_minor or 0
        update_fields = []

        if not order.subtotal_minor:
            order.subtotal_minor = legacy_total
            update_fields.append("subtotal_minor")
        if not order.total_minor:
            order.total_minor = legacy_total
            update_fields.append("total_minor")
        if not order.provider_reference and order.reference:
            order.provider_reference = order.reference
            update_fields.append("provider_reference")
        if order.status == "refunded" and not order.refunded_minor:
            order.refunded_minor = order.total_minor or legacy_total
            update_fields.append("refunded_minor")

        if update_fields:
            order.save(update_fields=update_fields + ["updated_at"])

        order_item = OrderItem.objects.filter(order_id=order.id).first()
        if not order_item and order.program_id:
            item_status = "pending"
            item_refunded_minor = 0
            if order.status == "paid":
                item_status = "paid"
            elif order.status == "refunded":
                item_status = "refunded"
                item_refunded_minor = order.total_minor or legacy_total
            elif order.status == "cancelled":
                item_status = "cancelled"
            elif order.status in {"failed", "expired"}:
                item_status = "failed"

            order_item = OrderItem.objects.create(
                order_id=order.id,
                program_id=order.program_id,
                program_name=order.program.name if order.program_id else "",
                program_code=order.program.code if order.program_id else "",
                currency=order.currency or "KES",
                amount_minor=order.total_minor or legacy_total,
                refunded_minor=item_refunded_minor,
                status=item_status,
                paid_at=order.paid_at,
                metadata={"migrated_from_legacy_order": True},
            )

        if not order_item:
            continue

        if order.status not in {"paid", "refunded"}:
            continue

        enrollment = None
        if order.enrollment_id:
            enrollment = Enrollment.objects.filter(pk=order.enrollment_id).first()
        if enrollment is None and order.program_id:
            enrollment = Enrollment.objects.filter(
                user_id=order.user_id,
                program_id=order.program_id,
            ).first()
        if enrollment is None and order.program_id:
            enrollment = Enrollment.objects.create(
                user_id=order.user_id,
                program_id=order.program_id,
                status="active" if order.status == "paid" else "suspended",
                access_source="paid",
                enrolled_at=order.paid_at or order.created_at,
            )
            if order.enrollment_id != enrollment.id:
                order.enrollment_id = enrollment.id
                order.save(update_fields=["enrollment", "updated_at"])

        grant, created = ProgramAccessGrant.objects.get_or_create(
            order_item_id=order_item.id,
            defaults={
                "user_id": order.user_id,
                "program_id": order.program_id,
                "enrollment_id": enrollment.id if enrollment else None,
                "source_type": "order_item",
                "status": "active" if order.status == "paid" else "revoked",
                "granted_at": order.paid_at or order.created_at,
                "revoked_at": order.updated_at if order.status == "refunded" else None,
                "expires_at": enrollment.expires_at if enrollment else None,
                "metadata": {"migrated_from_legacy_order": True},
            },
        )
        if created:
            continue

        grant_update_fields = []
        if grant.user_id != order.user_id:
            grant.user_id = order.user_id
            grant_update_fields.append("user")
        if grant.program_id != order.program_id:
            grant.program_id = order.program_id
            grant_update_fields.append("program")
        if enrollment and grant.enrollment_id != enrollment.id:
            grant.enrollment_id = enrollment.id
            grant_update_fields.append("enrollment")

        expected_status = "active" if order.status == "paid" else "revoked"
        if grant.status != expected_status:
            grant.status = expected_status
            grant_update_fields.append("status")
        expected_revoked_at = order.updated_at if order.status == "refunded" else None
        if grant.revoked_at != expected_revoked_at:
            grant.revoked_at = expected_revoked_at
            grant_update_fields.append("revoked_at")
        if grant_update_fields:
            grant.save(update_fields=grant_update_fields + ["updated_at"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_rename_orders_user_status_665f31_idx_orders_user_id_17dbdf_idx_and_more'),
        ('core', '0014_program_performance_indexes'),
        ('progression', '0007_enrollment_access_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked out'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commerce_carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='KES', max_length=8)),
            ],
            options={
                'db_table': 'commerce_cart_items',
            },
        ),
        migrations.CreateModel(
            name='CommerceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='default', max_length=32, unique=True)),
                ('enabled_payment_methods', models.JSONField(blank=True, default=apps.commerce.models.default_enabled_payment_methods)),
                ('offline_bank_details', models.JSONField(blank=True, default=dict)),
                ('offline_payment_instructions', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'commerce_configuration',
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commerce_order_events',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_name', models.CharField(max_length=255)),
                ('program_code', models.CharField(blank=True, default='', max_length=50)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('refunded_minor', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commerce_order_items',
            },
        ),
        migrations.CreateModel(
            name='ProgramAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(default='order_item', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commerce_program_access_grants',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('offline_bank_transfer', 'Offline bank transfer')], default='paystack', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('needs_attention', 'Needs attention'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('provider_refund_id', models.CharField(blank=True, default='', max_length=128)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commerce_refunds',
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commerce_refund_items',
            },
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_program_0dcab9_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_minor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_minor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_minor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_minor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='refund_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_minor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_orders', to='core.program'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('offline_bank_transfer', 'Offline bank transfer')], default='paystack', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending_payment', 'Pending payment'), ('pending_manual_payment', 'Pending manual payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], default='created', max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='commerce.order'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['refund_reference'], name='payment_web_refund__2fceb8_idx'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commerce.cart'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['currency', 'status'], name='orders_currenc_44aa81_idx'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.program'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_order_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commerce.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.program'),
        ),
        migrations.AddField(
            model_name='programaccessgrant',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants', to='progression.enrollment'),
        ),
        migrations.AddField(
            model_name='programaccessgrant',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grant', to='commerce.orderitem'),
        ),
        migrations.AddField(
            model_name='programaccessgrant',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.program'),
        ),
        migrations.AddField(
            model_name='programaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='commerce.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commerce.refund'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='commerce.refund'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['refund', 'created_at'], name='payment_att_refund__89cbd0_idx'),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_items', to='commerce.orderitem'),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.refund'),
        ),
        migrations.RunPython(backfill_commerce_data, noop_reverse),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status'], name='commerce_ca_user_id_0fb807_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='commerce_one_active_cart_per_user'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'created_at'], name='commerce_ca_cart_id_6adf96_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['program'], name='commerce_ca_program_8f34d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'program'), name='commerce_unique_cart_program'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'status'], name='commerce_or_order_i_ba13be_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['program', 'status'], name='commerce_or_program_be8d8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'program'), name='commerce_unique_order_program'),
        ),
        migrations.AddIndex(
            model_name='programaccessgrant',
            index=models.Index(fields=['user', 'program', 'status'], name='commerce_pr_user_id_e79787_idx'),
        ),
        migrations.AddIndex(
            model_name='programaccessgrant',
            index=models.Index(fields=['status', 'expires_at'], name='commerce_pr_status_16596c_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order', 'status'], name='commerce_re_order_i_4d7789_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['provider', 'provider_refund_id'], name='commerce_re_provide_ca295d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', 'created_at'], name='commerce_or_order_i_fd64a9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['refund', 'created_at'], name='commerce_or_refund__34fec6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['event_type'], name='commerce_or_event_t_d559b5_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['refund', 'status'], name='commerce_re_refund__d2be82_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['order_item', 'status'], name='commerce_re_order_i_72332c_idx'),
        ),
        migrations.AddConstraint(
            model_name='refunditem',
            constraint=models.UniqueConstraint(fields=('refund', 'order_item'), name='commerce_unique_refund_order_item'),
        ),
    ]
