# Generated by Django 5.2.13 on 2026-04-13 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_cart_cartitem_commerceconfiguration_orderevent_and_more'),
        ('core', '0014_program_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRevenueShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_bps', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commerce_program_revenue_shares',
            },
        ),
        migrations.CreateModel(
            name='RevenueLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_key', models.CharField(max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=16)),
                ('entry_type', models.CharField(choices=[('payment_share', 'Payment share'), ('refund_reversal', 'Refund reversal')], max_length=32)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('share_bps_snapshot', models.PositiveIntegerField(default=0)),
                ('settlement_party_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commerce_revenue_ledger_entries',
            },
        ),
        migrations.CreateModel(
            name='SettlementParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('instructor', 'Instructor'), ('partner', 'Partner')], max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('payout_method', models.CharField(choices=[('kepss', 'KEPSS bank account'), ('mobile_money', 'Mobile money')], max_length=32)),
                ('destination_details', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('paystack_recipient_code', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commerce_settlement_parties',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='paystack', max_length=32)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=32)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=128)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_beneficiary_payouts', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_beneficiary_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commerce_beneficiary_payouts',
            },
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='commerce.beneficiarypayout'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['payout', 'created_at'], name='payment_att_payout__d4d704_idx'),
        ),
        migrations.AddField(
            model_name='programrevenueshare',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_shares', to='core.program'),
        ),
        migrations.AddField(
            model_name='revenueledgerentry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='commerce.order'),
        ),
        migrations.AddField(
            model_name='revenueledgerentry',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='commerce.orderitem'),
        ),
        migrations.AddField(
            model_name='revenueledgerentry',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_ledger_entries', to='core.program'),
        ),
        migrations.AddField(
            model_name='revenueledgerentry',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='commerce.refund'),
        ),
        migrations.AddField(
            model_name='revenueledgerentry',
            name='refund_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='commerce.refunditem'),
        ),
        migrations.AddField(
            model_name='settlementparty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenueledgerentry',
            name='settlement_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='commerce.settlementparty'),
        ),
        migrations.AddField(
            model_name='programrevenueshare',
            name='settlement_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_revenue_shares', to='commerce.settlementparty'),
        ),
        migrations.AddField(
            model_name='beneficiarypayout',
            name='settlement_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='commerce.settlementparty'),
        ),
        migrations.AddIndex(
            model_name='settlementparty',
            index=models.Index(fields=['party_type', 'active'], name='commerce_se_party_t_6dc342_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementparty',
            index=models.Index(fields=['user', 'active'], name='commerce_se_user_id_cb00b6_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueledgerentry',
            index=models.Index(fields=['settlement_party', 'currency', 'direction'], name='commerce_re_settlem_2d9063_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueledgerentry',
            index=models.Index(fields=['order', 'entry_type'], name='commerce_re_order_i_dd6ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueledgerentry',
            index=models.Index(fields=['refund', 'entry_type'], name='commerce_re_refund__9d08b7_idx'),
        ),
        migrations.AddIndex(
            model_name='programrevenueshare',
            index=models.Index(fields=['program', 'active'], name='commerce_pr_program_74d6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='programrevenueshare',
            index=models.Index(fields=['settlement_party', 'active'], name='commerce_pr_settlem_ad1d9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='programrevenueshare',
            constraint=models.UniqueConstraint(fields=('program', 'settlement_party'), name='commerce_unique_program_settlement_party_share'),
        ),
        migrations.AddIndex(
            model_name='beneficiarypayout',
            index=models.Index(fields=['settlement_party', 'currency', 'status'], name='commerce_be_settlem_4fa2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiarypayout',
            index=models.Index(fields=['provider', 'provider_reference'], name='commerce_be_provide_8b1948_idx'),
        ),
    ]
