# Generated by Django 5.2.13 on 2026-04-14 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_programrevenueshare_revenueledgerentry_and_more'),
        ('core', '0014_program_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='core.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commerce_wishlist_items',
                'indexes': [models.Index(fields=['user', 'created_at'], name='commerce_wi_user_id_22d661_idx'), models.Index(fields=['program'], name='commerce_wi_program_8074c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'program'), name='commerce_unique_wishlist_user_program')],
            },
        ),
    ]
