import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('core', '0022_masterstudy_settings_fields'),
        ('progression', '0008_gamification_idempotency_and_streaks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomOAuthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_user_id', models.CharField(blank=True, default='', max_length=255)),
                ('google_email', models.EmailField(blank=True, default='', max_length=254)),
                ('refresh_token_ciphertext', models.TextField(blank=True, default='')),
                ('granted_scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('invalid', 'Invalid'), ('revoked', 'Revoked')], default='connected', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_classroom_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'google_classroom_oauth_credentials'},
        ),
        migrations.CreateModel(
            name='ClassroomCourseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom_course_id', models.CharField(max_length=255, unique=True)),
                ('classroom_name', models.CharField(max_length=255)),
                ('classroom_section', models.CharField(blank=True, default='', max_length=255)),
                ('enrollment_code', models.CharField(blank=True, default='', max_length=64)),
                ('alternate_link', models.URLField(blank=True, default='', max_length=1000)),
                ('course_state', models.CharField(blank=True, default='', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('sync_paused', models.BooleanField(default=False)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_category', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_classroom_link', to='core.program')),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_links', to='google_classroom.classroomoauthcredential')),
            ],
            options={'db_table': 'google_classroom_course_links'},
        ),
        migrations.CreateModel(
            name='ClassroomResourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_type', models.CharField(max_length=32)),
                ('local_id', models.CharField(max_length=255)),
                ('google_resource_type', models.CharField(max_length=32)),
                ('google_resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_integration', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('drift', 'Remote drift'), ('remote_deleted', 'Remote deleted'), ('unlinked', 'Unlinked')], default='active', max_length=24)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('remote_snapshot', models.JSONField(blank=True, default=dict)),
                ('remote_update_time', models.CharField(blank=True, default='', max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('course_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_mappings', to='google_classroom.classroomcourselink')),
            ],
            options={'db_table': 'google_classroom_resource_mappings'},
        ),
        migrations.CreateModel(
            name='ClassroomGradeSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_source_type', models.CharField(max_length=32)),
                ('local_source_id', models.CharField(max_length=255)),
                ('google_submission_id', models.CharField(blank=True, default='', max_length=255)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_category', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_classroom_grade_syncs', to='progression.enrollment')),
                ('resource_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_syncs', to='google_classroom.classroomresourcemapping')),
            ],
            options={
                'db_table': 'google_classroom_grade_syncs',
                'indexes': [models.Index(fields=['resource_mapping', 'status'], name='google_clas_resourc_abcab5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassroomRosterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_user_id', models.CharField(max_length=255)),
                ('verified_email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='student', max_length=16)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('invited', 'Invited'), ('conflict', 'Conflict'), ('removed', 'Removed')], default='matched', max_length=16)),
                ('course_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_mappings', to='google_classroom.classroomcourselink')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_classroom_mappings', to='progression.enrollment')),
                ('lms_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_classroom_roster_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_classroom_roster_mappings',
                'indexes': [models.Index(fields=['course_link', 'status'], name='google_clas_course__4fe941_idx')],
                'constraints': [models.UniqueConstraint(fields=('course_link', 'google_user_id'), name='google_classroom_unique_remote_roster_user')],
            },
        ),
        migrations.CreateModel(
            name='ClassroomRosterPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(max_length=32)),
                ('rows', models.JSONField(default=list)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_previews', to='google_classroom.classroomcourselink')),
            ],
            options={
                'db_table': 'google_classroom_roster_previews',
                'indexes': [models.Index(fields=['course_link', 'expires_at'], name='google_clas_course__873c5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassroomSyncAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_audits', to='google_classroom.classroomcourselink')),
            ],
            options={'db_table': 'google_classroom_sync_audits', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ClassroomSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('dead', 'Dead')], default='pending', max_length=16)),
                ('available_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=8)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('error_category', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_classroom_sync_jobs', to=settings.AUTH_USER_MODEL)),
                ('course_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='google_classroom.classroomcourselink')),
                ('resource_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='google_classroom.classroomresourcemapping')),
            ],
            options={
                'db_table': 'google_classroom_sync_jobs',
                'ordering': ['available_at', 'id'],
                'indexes': [
                    models.Index(fields=['status', 'available_at'], name='google_clas_status_a13ebe_idx'),
                    models.Index(fields=['course_link', 'job_type', 'status'], name='google_clas_course__8f400c_idx'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='classroomresourcemapping',
            index=models.Index(fields=['course_link', 'google_resource_type', 'status'], name='google_clas_course__0c787c_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomresourcemapping',
            constraint=models.UniqueConstraint(fields=('course_link', 'local_type', 'local_id'), name='google_classroom_unique_local_resource'),
        ),
    ]
