# Generated by Django 5.2.9 on 2026-01-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('hierarchy_structure', models.JSONField()),
                ('grading_logic', models.JSONField()),
                ('progression_rules', models.JSONField(blank=True, null=True)),
                ('gamification_enabled', models.BooleanField(default=False)),
                ('certificate_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'academic_blueprints',
                'indexes': [models.Index(fields=['name'], name='academic_bl_name_8b7090_idx')],
            },
        ),
    ]
