# Generated by Django 5.2.9 on 2025-12-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='academicblueprint',
            new_name='academic_bl_name_8b7090_idx',
            old_name='academic_bl_name_idx',
        ),
        migrations.AlterField(
            model_name='academicblueprint',
            name='grading_logic',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='academicblueprint',
            name='hierarchy_structure',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='academicblueprint',
            name='progression_rules',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
