# Generated by Django 5.2.9 on 2026-01-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicblueprint',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Mode-specific feature toggles'),
        ),
    ]
