# Generated by Django 5.2.9 on 2026-01-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0002_rename_academic_bl_name_idx_academic_bl_name_8b7090_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicblueprint',
            name='tenant',
        ),
    ]
