# Generated by Django 5.2.9 on 2026-01-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0001_initial'),
        ('certifications', '0001_initial'),
        ('progression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='progression.enrollment'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='blueprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_templates', to='blueprints.academicblueprint'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certifications.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='certifications.certificate'),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['blueprint'], name='cert_tmpl_blueprint_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['is_default'], name='cert_tmpl_is_default_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['serial_number'], name='cert_serial_number_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['enrollment'], name='cert_enrollment_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_revoked'], name='cert_is_revoked_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['serial_number_queried'], name='verif_serial_queried_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['verified_at'], name='verif_verified_at_idx'),
        ),
    ]
