# Generated by Django 5.2.9 on 2026-01-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
