# Generated by Django 5.2.13 on 2026-04-15 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_certificate_updated_at_verificationlog_updated_at'),
        ('progression', '0007_enrollment_access_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Release'), ('released', 'Released'), ('ineligible', 'Ineligible')], default='ineligible', max_length=20)),
                ('eligible_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('eligibility_snapshot', models.JSONField(blank=True, default=dict)),
                ('certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_record', to='certifications.certificate')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_eligibility', to='progression.enrollment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_certificate_eligibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificate_eligibility_queue',
                'indexes': [models.Index(fields=['status'], name='cert_queue_status_idx'), models.Index(fields=['eligible_at'], name='cert_queue_eligible_at_idx')],
            },
        ),
    ]
