from django.db import migrations


def element(
    element_id,
    element_type,
    x,
    y,
    width,
    height,
    content="",
    *,
    font_size=18,
    font_weight=400,
    color="#172033",
    align="center",
    z_index=1,
    **extra,
):
    custom_styles = extra.pop("styles", {})
    letter_spacing = extra.pop("letterSpacing", 0)
    styles = {
        "fontFamily": "Albert Sans",
        "fontSize": font_size,
        "fontWeight": font_weight,
        "color": color,
        "textAlign": align,
        "lineHeight": 1.2,
        "letterSpacing": letter_spacing,
    }
    styles.update(custom_styles)

    return {
        "id": element_id,
        "type": element_type,
        "x": x,
        "y": y,
        "width": width,
        "height": height,
        "rotation": 0,
        "locked": False,
        "hidden": False,
        "zIndex": z_index,
        "content": content,
        "styles": styles,
        **extra,
    }


def layout(background, elements, *, accent, border=None):
    return {
        "schemaVersion": 1,
        "background": {
            "color": background,
            "image": None,
        },
        "safeAreaMm": 10,
        "theme": {
            "accent": accent,
            "border": border or accent,
        },
        "elements": elements,
    }


def starter_definitions():
    return [
        {
            "key": "classic-formal",
            "name": "Classic Formal",
            "description": "A traditional framed award for formal qualifications.",
            "orientation": "landscape",
            "width": 297,
            "height": 210,
            "layout": layout(
                "#fffdf8",
                [
                    element(
                        "classic-border",
                        "shape",
                        8,
                        8,
                        281,
                        194,
                        color="#9a7732",
                        z_index=0,
                        shape="border",
                        styles={
                            "fill": "transparent",
                            "stroke": "#9a7732",
                            "strokeWidth": 1.5,
                        },
                    ),
                    element(
                        "classic-kicker",
                        "text",
                        48,
                        35,
                        201,
                        10,
                        "CERTIFICATE OF ACHIEVEMENT",
                        font_size=13,
                        font_weight=700,
                        color="#9a7732",
                        letterSpacing=2,
                    ),
                    element(
                        "classic-title",
                        "dynamic_text",
                        35,
                        58,
                        227,
                        24,
                        "{{student_name}}",
                        font_size=31,
                        font_weight=600,
                        color="#20242f",
                    ),
                    element(
                        "classic-copy",
                        "text",
                        59,
                        91,
                        179,
                        10,
                        "has successfully completed",
                        font_size=12,
                        color="#626b7a",
                    ),
                    element(
                        "classic-course",
                        "dynamic_text",
                        42,
                        108,
                        213,
                        19,
                        "{{program_title}}",
                        font_size=22,
                        font_weight=600,
                        color="#9a7732",
                    ),
                    element(
                        "classic-date",
                        "dynamic_text",
                        51,
                        150,
                        75,
                        10,
                        "Issued {{issue_date}}",
                        font_size=10,
                        color="#626b7a",
                        align="left",
                    ),
                    element(
                        "classic-signature-line",
                        "line",
                        177,
                        147,
                        70,
                        1,
                        color="#9a7732",
                        styles={"stroke": "#9a7732", "strokeWidth": 0.8},
                    ),
                    element(
                        "classic-instructor",
                        "dynamic_text",
                        177,
                        153,
                        70,
                        9,
                        "{{instructor_name}}",
                        font_size=10,
                    ),
                    element(
                        "classic-code",
                        "dynamic_text",
                        100,
                        182,
                        97,
                        7,
                        "Certificate {{serial_number}}",
                        font_size=8,
                        color="#7d8490",
                    ),
                ],
                accent="#9a7732",
            ),
        },
        {
            "key": "modern-blue",
            "name": "Modern Blue",
            "description": "A confident contemporary layout with a strong colour panel.",
            "orientation": "landscape",
            "width": 297,
            "height": 210,
            "layout": layout(
                "#f6f9ff",
                [
                    element(
                        "modern-panel",
                        "shape",
                        0,
                        0,
                        73,
                        210,
                        z_index=0,
                        shape="rectangle",
                        styles={"fill": "#2457d6", "stroke": "transparent"},
                    ),
                    element(
                        "modern-mark",
                        "text",
                        16,
                        24,
                        41,
                        22,
                        "AWARD",
                        font_size=22,
                        font_weight=700,
                        color="#ffffff",
                        align="left",
                    ),
                    element(
                        "modern-kicker",
                        "text",
                        91,
                        33,
                        171,
                        9,
                        "CERTIFICATE OF COMPLETION",
                        font_size=11,
                        font_weight=700,
                        color="#2457d6",
                        align="left",
                        letterSpacing=1.4,
                    ),
                    element(
                        "modern-copy",
                        "text",
                        91,
                        61,
                        171,
                        8,
                        "Proudly presented to",
                        font_size=11,
                        color="#6c7890",
                        align="left",
                    ),
                    element(
                        "modern-student",
                        "dynamic_text",
                        91,
                        76,
                        176,
                        25,
                        "{{student_name}}",
                        font_size=30,
                        font_weight=700,
                        color="#15203b",
                        align="left",
                    ),
                    element(
                        "modern-course-copy",
                        "text",
                        91,
                        112,
                        171,
                        8,
                        "for completing",
                        font_size=10,
                        color="#6c7890",
                        align="left",
                    ),
                    element(
                        "modern-course",
                        "dynamic_text",
                        91,
                        125,
                        176,
                        18,
                        "{{program_title}}",
                        font_size=20,
                        font_weight=600,
                        color="#2457d6",
                        align="left",
                    ),
                    element(
                        "modern-date",
                        "dynamic_text",
                        91,
                        169,
                        70,
                        9,
                        "{{issue_date}}",
                        font_size=10,
                        color="#536078",
                        align="left",
                    ),
                    element(
                        "modern-code",
                        "dynamic_text",
                        177,
                        169,
                        90,
                        9,
                        "{{serial_number}}",
                        font_size=9,
                        color="#536078",
                        align="right",
                    ),
                ],
                accent="#2457d6",
            ),
        },
        {
            "key": "minimal-professional",
            "name": "Minimal Professional",
            "description": "A restrained, spacious design for professional learning.",
            "orientation": "landscape",
            "width": 297,
            "height": 210,
            "layout": layout(
                "#ffffff",
                [
                    element(
                        "minimal-accent",
                        "line",
                        23,
                        25,
                        32,
                        2,
                        z_index=0,
                        styles={"stroke": "#169873", "strokeWidth": 2},
                    ),
                    element(
                        "minimal-kicker",
                        "text",
                        23,
                        42,
                        130,
                        9,
                        "CERTIFICATE",
                        font_size=11,
                        font_weight=700,
                        color="#169873",
                        align="left",
                        letterSpacing=2.5,
                    ),
                    element(
                        "minimal-heading",
                        "text",
                        23,
                        63,
                        210,
                        18,
                        "Recognition of completion",
                        font_size=24,
                        font_weight=600,
                        color="#17252e",
                        align="left",
                    ),
                    element(
                        "minimal-copy",
                        "text",
                        23,
                        91,
                        130,
                        8,
                        "This certificate is awarded to",
                        font_size=10,
                        color="#758087",
                        align="left",
                    ),
                    element(
                        "minimal-student",
                        "dynamic_text",
                        23,
                        106,
                        218,
                        22,
                        "{{student_name}}",
                        font_size=28,
                        font_weight=600,
                        color="#17252e",
                        align="left",
                    ),
                    element(
                        "minimal-course",
                        "dynamic_text",
                        23,
                        139,
                        218,
                        15,
                        "{{program_title}}",
                        font_size=17,
                        font_weight=500,
                        color="#169873",
                        align="left",
                    ),
                    element(
                        "minimal-meta",
                        "dynamic_text",
                        23,
                        175,
                        218,
                        8,
                        "Issued {{issue_date}}  ·  {{serial_number}}",
                        font_size=9,
                        color="#758087",
                        align="left",
                    ),
                ],
                accent="#169873",
            ),
        },
        {
            "key": "academic-gold",
            "name": "Academic Gold",
            "description": "A portrait award inspired by academic honours and ceremonies.",
            "orientation": "portrait",
            "width": 210,
            "height": 297,
            "layout": layout(
                "#fcfaf5",
                [
                    element(
                        "academic-border",
                        "shape",
                        9,
                        9,
                        192,
                        279,
                        z_index=0,
                        shape="border",
                        styles={
                            "fill": "transparent",
                            "stroke": "#b78a35",
                            "strokeWidth": 1.2,
                        },
                    ),
                    element(
                        "academic-mark",
                        "shape",
                        82,
                        32,
                        46,
                        46,
                        z_index=1,
                        shape="circle",
                        styles={"fill": "#b78a35", "stroke": "transparent"},
                    ),
                    element(
                        "academic-kicker",
                        "text",
                        33,
                        95,
                        144,
                        10,
                        "CERTIFICATE OF EXCELLENCE",
                        font_size=11,
                        font_weight=700,
                        color="#b78a35",
                        letterSpacing=1.5,
                    ),
                    element(
                        "academic-copy",
                        "text",
                        42,
                        124,
                        126,
                        9,
                        "Presented with distinction to",
                        font_size=10,
                        color="#6e685e",
                    ),
                    element(
                        "academic-student",
                        "dynamic_text",
                        25,
                        142,
                        160,
                        29,
                        "{{student_name}}",
                        font_size=27,
                        font_weight=600,
                        color="#25221d",
                    ),
                    element(
                        "academic-course",
                        "dynamic_text",
                        29,
                        190,
                        152,
                        22,
                        "{{program_title}}",
                        font_size=18,
                        font_weight=600,
                        color="#b78a35",
                    ),
                    element(
                        "academic-date",
                        "dynamic_text",
                        45,
                        237,
                        120,
                        9,
                        "Awarded {{issue_date}}",
                        font_size=9,
                        color="#6e685e",
                    ),
                    element(
                        "academic-code",
                        "dynamic_text",
                        45,
                        264,
                        120,
                        8,
                        "{{serial_number}}",
                        font_size=8,
                        color="#8c857a",
                    ),
                ],
                accent="#b78a35",
            ),
        },
        {
            "key": "participation",
            "name": "Participation",
            "description": "A friendly, versatile certificate for events and short courses.",
            "orientation": "landscape",
            "width": 297,
            "height": 210,
            "layout": layout(
                "#fffaf5",
                [
                    element(
                        "participation-corner",
                        "shape",
                        0,
                        0,
                        98,
                        58,
                        z_index=0,
                        shape="organic",
                        styles={"fill": "#ef6b4d", "stroke": "transparent"},
                    ),
                    element(
                        "participation-dot",
                        "shape",
                        245,
                        147,
                        52,
                        63,
                        z_index=0,
                        shape="circle",
                        styles={"fill": "#f4bd4d", "stroke": "transparent"},
                    ),
                    element(
                        "participation-kicker",
                        "text",
                        36,
                        44,
                        225,
                        10,
                        "CERTIFICATE OF PARTICIPATION",
                        font_size=12,
                        font_weight=700,
                        color="#ef6b4d",
                        letterSpacing=1.3,
                    ),
                    element(
                        "participation-copy",
                        "text",
                        62,
                        72,
                        173,
                        8,
                        "This recognition is presented to",
                        font_size=10,
                        color="#796a61",
                    ),
                    element(
                        "participation-student",
                        "dynamic_text",
                        36,
                        88,
                        225,
                        26,
                        "{{student_name}}",
                        font_size=30,
                        font_weight=700,
                        color="#29201c",
                    ),
                    element(
                        "participation-course",
                        "dynamic_text",
                        47,
                        127,
                        203,
                        18,
                        "{{program_title}}",
                        font_size=20,
                        font_weight=600,
                        color="#ef6b4d",
                    ),
                    element(
                        "participation-date",
                        "dynamic_text",
                        55,
                        169,
                        92,
                        9,
                        "{{issue_date}}",
                        font_size=9,
                        color="#796a61",
                    ),
                    element(
                        "participation-code",
                        "dynamic_text",
                        150,
                        169,
                        92,
                        9,
                        "{{serial_number}}",
                        font_size=9,
                        color="#796a61",
                    ),
                ],
                accent="#ef6b4d",
            ),
        },
    ]


def seed_starters(apps, schema_editor):
    CertificateTemplate = apps.get_model("certifications", "CertificateTemplate")
    CertificateTemplateVersion = apps.get_model(
        "certifications",
        "CertificateTemplateVersion",
    )

    for starter in starter_definitions():
        existing = CertificateTemplate.objects.filter(
            is_starter=True,
            name=starter["name"],
        ).first()
        if existing:
            continue

        template = CertificateTemplate.objects.create(
            name=starter["name"],
            template_html="",
            visibility="system",
            status="published",
            is_starter=True,
            current_version_number=1,
            metadata={
                "builderSeedKey": starter["key"],
                "description": starter["description"],
                "seededBy": "certificate-builder-v1",
            },
        )
        CertificateTemplateVersion.objects.create(
            template=template,
            version_number=1,
            orientation=starter["orientation"],
            width_mm=starter["width"],
            height_mm=starter["height"],
            layout=starter["layout"],
            is_published=True,
        )


def remove_starters(apps, schema_editor):
    CertificateTemplate = apps.get_model("certifications", "CertificateTemplate")
    CertificateTemplate.objects.filter(
        is_starter=True,
        metadata__seededBy="certificate-builder-v1",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0005_visual_template_versions"),
    ]

    operations = [
        migrations.RunPython(seed_starters, reverse_code=remove_starters),
    ]
