export const tokens = {
  ink: '#14213D',
  inkSoft: '#3A4564',
  paper: '#F3F5FA',
  card: '#FFFFFF',
  blue: '#1D4ED8',
  blueDeep: '#12318C',
  red: '#B91C1C',
  redDeep: '#7F1313',
  hairline: '#DADFE8',
  muted: '#6B7280',
  fontDisplay: "'Space Grotesk', sans-serif",
  fontBody: "'IBM Plex Sans', sans-serif",
  fontMono: "'IBM Plex Mono', monospace",
};
